[package]
name = "waywin"
version = "0.1.0"
edition = "2021"

[dependencies]
windows-sys = { version = "0.59.0", features = [
    "Win32_System_LibraryLoader",
    "Win32_UI_HiDpi",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Graphics_Gdi",
    "Win32_Graphics_Dwm",
] }
log = "0.4.22"
raw-window-handle = "0.6.2"
windows-result = "0.2.0"

[dev-dependencies]
colog = "1.3.0"
pollster = "0.4.0"
wgpu = "23.0.0"
